name: "Build and Release"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        os: [linux]
        go-version: [1.22.x]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o build/flower-${{ matrix.os }}-${{ matrix.arch }} ./cmd/flower

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: flower-${{ matrix.os }}-${{ matrix.arch }}
          path: build/flower-${{ matrix.os }}-${{ matrix.arch }}
          compression-level: 1
          if-no-files-found: error
