name: Go CI
on:
  # Trigger the workflow on any push to the repository
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Go environment
        uses: Rethunk-Tech/gh-actions/setup-go@e04e0afa3e00c59e33030fdbc7df29c15000357b # v1.7
        with:
          run-lint: "true"
          run-govulncheck: "true"

      - name: Download modules
        run: go mod download

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Go environment
        uses: Rethunk-Tech/gh-actions/setup-go@e04e0afa3e00c59e33030fdbc7df29c15000357b # v1.7

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./... | tee TestResults.log

      - name: Upload Test Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: TestResults-${{ matrix.os }}
          path: TestResults.log
