name: Go CI
on:
  # Trigger the workflow on any push to the repository
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Go environment
        uses: Rethunk-Tech/gh-actions/setup-go@ea87a602a5214e1fb513feb22a035b7e0f3b9245 # v1.5
        with:
          run-lint: "true"
          lint-version: v2.12

      - name: Download modules
        run: go mod download

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Go environment
        uses: Rethunk-Tech/gh-actions/setup-go@ea87a602a5214e1fb513feb22a035b7e0f3b9245 # v1.5

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./... | tee TestResults.log

      - name: Upload Test Results
        uses: actions/upload-artifact@v7
        with:
          name: TestResults-${{ matrix.os }}
          path: TestResults.log
