name: Go CI
on:
  # Trigger the workflow on a push with a tag starting with 'v'
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: ["1.22.x"]
        arch: [amd64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Build binary
        run: |
          mkdir -p build/${{ matrix.os }}-${{ matrix.arch }}
          GOOS=$(if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then echo "linux"; else echo "windows"; fi) GOARCH=${{ matrix.arch }} go build -v \
            -o build/${{ matrix.os }}-${{ matrix.arch }}/app \
            ./cmd/flower

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: build/${{ matrix.os }}-${{ matrix.arch }}/app

  release:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: build

      # Without this, "gh" explodes spectacularily
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          tagname="${GITHUB_REF#refs/tags/}"
          echo "Tag name is $tagname"
          echo "Uploading release assets..."
          ls -lR build/*
          files=$(for f in build/*; do echo -n " $f\#"; echo -n $f | sed -e s/build\\/// -e s/latest-// ; done)
          echo "Files are $files"
          gh release create "$tagname" -t "$tagname" $files
